name: onlyoffice-documentserver
version: "1.1"
summary: "An office suite that allowing to create, view and edit documents."
description: "ONLYOFFICE onlyoffice-documentserver"
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
base: core18
architectures:
  - amd64

apps:
  onlyoffice-documentserver:
    adapter: full
    command: usr/sbin/documentserver-start.sh
    daemon: simple
    plugs:
      - home
      - desktop
      - desktop-legacy
      - network
      - network-bind
      - locale-control
      - browser-support
      - removable-media

  node:
    command: bin/node
    adapter: full
    plugs: [network, network-bind, removable-media]
  
  nginx:
    command: usr/sbin/nginx-start.sh
    daemon: simple
    restart-condition: always
    plugs: [network, network-bind, removable-media]

  rabbitmq:
    command: usr/lib/rabbitmq/bin/rabbitmq-server
    daemon: simple
    plugs: [network, network-bind, removable-media]

  redis:
    command: redis-server
    daemon: simple
    plugs: [network, network-bind, removable-media]

hooks:
  configure:
    plugs: [network, network-bind]

parts:
  rabbitmq:
    plugin: dump
    source: https://github.com/rabbitmq/rabbitmq-server/releases/download/rabbitmq_v3_6_15/rabbitmq-server_3.6.15-1_all.deb
    source-type: deb
    stage-packages:
      - erlang
    override-build: |
      snapcraftctl build
      # rabbitmq-server
      sed -i -e 's/rabbitmq-env/rabbitmq-env.sh/g' $SNAPCRAFT_PART_INSTALL/usr/lib/rabbitmq/lib/rabbitmq_server-3.6.15/sbin/rabbitmq-server
      #mv $SNAPCRAFT_PART_INSTALL/usr/lib/rabbitmq/lib/rabbitmq_server-3.6.15/sbin/rabbitmq-env $SNAPCRAFT_PART_INSTALL/usr/lib/rabbitmq/lib/rabbitmq_server-3.6.15/sbin/rabbitmq-env-old
      sed -i -e 's/ROOTDIR=/ROOTDIR=$SNAP/g' $SNAPCRAFT_PART_INSTALL/usr/lib/erlang/bin/erl

  onlyoffice-documentserver:
    plugin: dump
    source: http://download.onlyoffice.com/install/documentserver/linux/onlyoffice-documentserver-ie_amd64.deb #snap/onlyoffice-documentserver-ie_5.3.4-3_amd64.deb
    source-type: deb
    stage-packages:
      - libcurl3
      - libxml2
      - fonts-dejavu
      - fonts-liberation
      - ttf-mscorefonts-installer
      - fonts-crosextra-carlito
      - fonts-takao-gothic
      - fonts-opensymbol
      - create-resources
      - libreadline-dev
      - libc-bin
      - locales-all
      - locales
      - libc6
      #- postgresql-client-common
      #- perl
    #stage-snaps:
      #- postgresql96
    override-build: |
      rm -f lib/libicuuc.so.58
      rm -f lib/libPdfWriter.so
      rm -f lib/libdoctrenderer.so
      rm -f lib/libHtmlFile.so
      rm -f lib/libHtmlRenderer.so
      rm -f lib/libPdfReader.so
      rm -f lib/libkernel.so
      rm -f lib/libXpsFile.so
      rm -f lib/libDjVuFile.so
      rm -f lib/libUnicodeConverter.so
      rm -f lib/libicudata.so.58
      rm -f lib/libgraphics.so
      snapcraftctl build
      # posgresql
      cp $SNAPCRAFT_PART_INSTALL/lib/x86_64-linux-gnu/libreadline.so.7.0 $SNAPCRAFT_PART_INSTALL/lib/x86_64-linux-gnu/libreadline.so.6
      # edition supervisor/* && /supervisord.conf ds-example.conf
      sed -i -e 's/\/var\/www/%(ENV_SNAP)s\/var\/www/g' $SNAPCRAFT_PART_INSTALL/etc/onlyoffice/documentserver/supervisor/*
      sed -i -e 's/\/etc/%(ENV_SNAP)s\/etc/g' $SNAPCRAFT_PART_INSTALL/etc/onlyoffice/documentserver/supervisor/*
      sed -i -e 's/\/var\/log/%(ENV_SNAP_DATA)s\/var\/log/g' $SNAPCRAFT_PART_INSTALL/etc/onlyoffice/documentserver/supervisor/*
      sed -i -e 's/\/var\/www/%(ENV_SNAP)s\/var\/www/g' $SNAPCRAFT_PART_INSTALL/etc/onlyoffice/documentserver-example/supervisor/ds-example.conf
      sed -i -e 's/\/etc/%(ENV_SNAP)s\/etc/g' $SNAPCRAFT_PART_INSTALL/etc/onlyoffice/documentserver-example/supervisor/ds-example.conf
      sed -i -e 's/\/var\/log/%(ENV_SNAP_DATA)s\/var\/log/g' $SNAPCRAFT_PART_INSTALL/etc/onlyoffice/documentserver-example/supervisor/ds-example.conf
      sed -i -e 's/user=ds/;user=ds/g' $SNAPCRAFT_PART_INSTALL/etc/onlyoffice/documentserver/supervisor/*
      sed -i -e 's/user=ds/;user=ds/g' $SNAPCRAFT_PART_INSTALL/etc/onlyoffice/documentserver-example/supervisor/*
      # edition etc/onlyoffice/documentserver/nginx/ds...
      sed -i -e 's/etc/snap\/onlyoffice-documentserver\/current\/etc/g' $SNAPCRAFT_PART_INSTALL/etc/onlyoffice/documentserver/nginx/ds.conf
      mkdir -p $SNAPCRAFT_PART_INSTALL/etc/nginx/conf.d
      cp $SNAPCRAFT_PART_INSTALL/etc/onlyoffice/documentserver/nginx/ds.conf $SNAPCRAFT_PART_INSTALL/etc/nginx/conf.d/ds.conf
      sed -i -e 's/var\/log\/onlyoffice\/documentserver\/nginx.error.log/var\/snap\/onlyoffice-documentserver\/current\/var\/log\/onlyoffice\/documentserver\/nginx.error.log/g' $SNAPCRAFT_PART_INSTALL/etc/onlyoffice/documentserver/nginx/includes/ds-common.conf
      sed -i -e 's/var\/www/snap\/onlyoffice-documentserver\/current\/var\/www/g' $SNAPCRAFT_PART_INSTALL/etc/onlyoffice/documentserver/nginx/includes/ds-docservice.conf
      sed -i -e 's/var\/lib/var\/snap\/onlyoffice-documentserver\/common\/var\/lib/g' $SNAPCRAFT_PART_INSTALL/etc/onlyoffice/documentserver/nginx/includes/ds-docservice.conf
      sed -i -e 's/var/snap\/onlyoffice-documentserver\/current\/var/g' $SNAPCRAFT_PART_INSTALL/etc/onlyoffice/documentserver-example/nginx/includes/ds-example.conf
      # edition documentserver && documentserver-example
      mv $SNAPCRAFT_PART_INSTALL/etc/onlyoffice/documentserver/production-linux.json $SNAPCRAFT_PART_INSTALL/etc/onlyoffice/documentserver/production-linux.json-old
      mv $SNAPCRAFT_PART_INSTALL/etc/supervisor/conf.d/ds-example.conf $SNAPCRAFT_PART_INSTALL/etc/supervisor/conf.d/ds-example.conf-old
      sed -i -e 's/web-apps/snap\/onlyoffice-documentserver\/current\/var\/www\/onlyoffice\/documentserver\/web-apps/g' $SNAPCRAFT_PART_INSTALL/etc/onlyoffice/documentserver-example/default.json
      # copy lib
      cp $SNAPCRAFT_PART_INSTALL/var/www/onlyoffice/documentserver/server/FileConverter/bin/*.so $SNAPCRAFT_PART_INSTALL/lib/
      cp $SNAPCRAFT_PART_INSTALL/var/www/onlyoffice/documentserver/server/FileConverter/bin/libicuuc.so.58 $SNAPCRAFT_PART_INSTALL/lib/
      cp $SNAPCRAFT_PART_INSTALL/var/www/onlyoffice/documentserver/server/FileConverter/bin/libicudata.so.58 $SNAPCRAFT_PART_INSTALL/lib/
      # mv docManager.js and default.json
      mv $SNAPCRAFT_PART_INSTALL/var/www/onlyoffice/documentserver-example/helpers/docManager.js $SNAPCRAFT_PART_INSTALL/var/www/onlyoffice/documentserver-example/helpers/docManager.js-old
      mv $SNAPCRAFT_PART_INSTALL/etc/onlyoffice/documentserver-example/default.json $SNAPCRAFT_PART_INSTALL/etc/onlyoffice/documentserver-example/default.json-old
      # documentserver-generate-allfonts.sh
      sed -i -e 's/DIR="/DIR="$SNAPCRAFT_PART_INSTALL/g' $SNAPCRAFT_PART_INSTALL/usr/bin/documentserver-generate-allfonts.sh
      sed -i -e 's/echo -n Generating AllFonts.js, please wait.../echo -n Generating AllFonts.js, please wait...\nexport LD_LIBRARY_PATH="\$LD_LIBRARY_PATH:\$SNAPCRAFT_PART_INSTALL\/lib:$LD_LIBRARY_PATH"/g' $SNAPCRAFT_PART_INSTALL/usr/bin/documentserver-generate-allfonts.sh
      sed -i -e 's/--use-system="true"/--use-system="false"/g' $SNAPCRAFT_PART_INSTALL/usr/bin/documentserver-generate-allfonts.sh
      sed -i -e 's/chown/#chown/g' $SNAPCRAFT_PART_INSTALL/usr/bin/documentserver-generate-allfonts.sh
      mkdir -p $SNAPCRAFT_PART_INSTALL/var/www/onlyoffice/documentserver/fonts
      DIR="$SNAPCRAFT_PART_INSTALL/var/www/onlyoffice/documentserver"
      "$DIR/server/tools/AllFontsGen" --input="$DIR/core-fonts"  --allfonts-web="$DIR/sdkjs/common/AllFonts.js"  --allfonts="$DIR/server/FileConverter/bin/AllFonts.js"  --images="$DIR/sdkjs/common/Images"   --selection="$DIR/server/FileConverter/bin/font_selection.bin"  --output-web="$DIR/fonts"  --use-system="false"


  node:
    plugin: dump
    source: https://nodejs.org/dist/v8.12.0/node-v8.12.0-linux-x64.tar.gz
    override-build: |
      snapcraftctl build
      rm -f $SNAPCRAFT_PART_INSTALL/README.md

  nginx:
    plugin: dump
    source: https://github.com/seanlano/nginx.git
    source-type: git
    source-tag: release-1.13.6_snap-fix
    stage-packages:
      - supervisor
      - redis-server
    override-build: |
      snapcraftctl build
      wget https://sourceforge.net/projects/libpng/files/zlib/1.2.11/zlib-1.2.11.tar.gz/download -O zlib.tar.gz
      mkdir zlib
      tar xvf zlib.tar.gz --strip-components 1 -C zlib/
      wget https://ftp.pcre.org/pub/pcre/pcre-8.41.tar.bz2 -O pcre.tar.bz2
      mkdir pcre
      tar xvf pcre.tar.bz2 --strip-components 1 -C pcre/
      auto/configure --prefix=/snap/onlyoffice-documentserver/current/etc/nginx --sbin-path=/snap/onlyoffice-documentserver/current/usr/sbin --conf-path=/var/snap/onlyoffice-documentserver/current/etc/nginx/nginx.conf --error-log-path=/var/snap/onlyoffice-documentserver/current/var/log/nginx/error.log --http-log-path=/var/snap/onlyoffice-documentserver/current/var/log/nginx/access.log --pid-path=/var/snap/onlyoffice-documentserver/current/var/run/nginx.pid --lock-path=/var/snap/onlyoffice-documentserver/current/var/lock/nginx.lock --http-client-body-temp-path=/var/snap/onlyoffice-documentserver/current/var/cache/nginx/client_temp --http-proxy-temp-path=/var/snap/onlyoffice-documentserver/current/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/snap/onlyoffice-documentserver/current/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/snap/onlyoffice-documentserver/current/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/snap/onlyoffice-documentserver/current/var/cache/nginx/scgi_temp --with-http_secure_link_module
      make
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp objs/nginx $SNAPCRAFT_PART_INSTALL/bin/nginx
      mkdir -p $SNAPCRAFT_PART_INSTALL/etc/nginx
      cp conf/* $SNAPCRAFT_PART_INSTALL/etc/nginx
      mkdir -p $SNAPCRAFT_PART_INSTALL/etc/nginx/conf.d
      ###########################################################
      #cp /root/parts/onlyoffice-documentserver/install/etc/onlyoffice/documentserver/nginx/ds.conf $SNAPCRAFT_PART_INSTALL/etc/nginx/conf.d/ds.conf
      ###########################################################
      rm -f etc/nginx/modules
      rm $SNAPCRAFT_PART_INSTALL/etc/nginx/nginx.conf
      #rm -f $SNAPCRAFT_PART_INSTALL/etc/nginx/conf.d/default.conf
      ################################
      sed -i -e 's/\/var/%(ENV_SNAP_DATA)s\/var/g' $SNAPCRAFT_PART_INSTALL/etc/supervisor/supervisord.conf
      sed -i -e 's/\/etc/%(ENV_SNAP)s\/etc/g' $SNAPCRAFT_PART_INSTALL/etc/supervisor/supervisord.conf
      sed -i -e 's/chmod=0700/chmod=0777\nchown root:root/g' $SNAPCRAFT_PART_INSTALL/etc/supervisor/supervisord.conf
      sed -i -e 's/usr\/sbin\/nginx/snap\/onlyoffice-documentserver\/current\/usr\/sbin\/nginx/g' $SNAPCRAFT_PART_INSTALL/etc/init.d/supervisor
      sed -i -e 's/etc/snap\/onlyoffice-documentserver\/current\/etc/g' $SNAPCRAFT_PART_INSTALL/etc/init.d/supervisor
      sed -i -e 's/lib/snap\/onlyoffice-documentserver\/current\/lib/g' $SNAPCRAFT_PART_INSTALL/etc/init.d/supervisor
    build-packages:
      - libc6
      - libgd3
      - libgeoip1
      - libssl1.0.0
      - libxml2
      - libxslt1.1
      - build-essential
      - autoconf
      - automake
      - pkg-config
      - libtool
      - libpcre3-dev
      - libpcre++-dev
      - zlibc 
      - zlib1g
      - zlib1g-dev
      - wget


  starter:
    plugin: dump
    source: ./config/
    organize:
      production-linux.json: etc/onlyoffice/documentserver/production-linux.json
      ds-example.conf: etc/supervisor/conf.d/ds-example.conf
      default.json: etc/onlyoffice/documentserver-example/default.json
      nginx.conf: etc/nginx/nginx.conf

  bin:
    plugin: dump
    source: ./bin/
    organize:
      documentserver-start.sh: usr/sbin/documentserver-start.sh
      rabbitmq-env.sh: usr/lib/rabbitmq/bin/rabbitmq-env.sh
      nginx-start.sh: usr/sbin/nginx-start.sh